eps/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    ###------------------------------------------------------Paginas:-----------------------------------------------------------###
    #Pagina principal
    url(r'^home','epsapp.views.home',name='home'),

    #Informacion de envio
    url(r'^rastreo','epsapp.views.tracking',name='tracking'),

    ###------------------------------------------------------Empleados:---------------------------------------------------------###
    url(r'^appeps$','epsapp.views.empmain',name='empmain'),                     #Principal empleado
    url(r'^appeps/iniciarsesion$','epsapp.views.emplogin',name='emplogin'),     #Iniciar sesion
    url(r'^appeps/cerrarsesion$','epsapp.views.emplogout',name='emplogout'),    #Cerrar sesion
    
    ###------------------------------------------------------Gerentes--------------------------------------###

    url(r'^appeps/gerente$','epsapp.views.manager',name='manager'),                                                         #Principal gerente
    
    url(r'^appeps/gerente/solicitudes$','epsapp.views.alldelrequest_man',name='alldelrequest_man'),                         #Todas las solicitudes
    url(r'^appeps/gerente/solicitudes/(?P<requestid>\d+)$','epsapp.views.requestdetail_man',name='requestdetail_man'),      #Una solicitud
    url(r'^appeps/gerente/solicitudes/borrar/(?P<requestid>\d+)$','epsapp.views.deletereq',name='deletereq'),               #Borrar solicitud
    url(r'^appeps/gerente/solicitudes/actualizar/(?P<requestid>\d+)$','epsapp.views.updatereq_man',name='updatereq_man'),   #Actualizar solicitud
    
    url(r'^appeps/gerente/buscar$','epsapp.views.searchreq',name='searchreq'),                                              #Buscar solicitud
    
    url(r'^appeps/gerente/facturas$','epsapp.views.bills',name='bills'),                                                    #Lista de facturas
    url(r'^appeps/gerente/facturas/(?P<billid>\d+)$','epsapp.views.billdetail',name='billdetail'),                          #Detalles de una factura
    url(r'^appeps/gerente/reportes$','epsapp.views.reports',name='reports'),
    url(r'^appeps/gerente/reportes/crear$','epsapp.views.newreport',name='newreport'),                                                   #Reportes
    url(r'^appeps/gerente/reportes/(?P<reportid>\d+)$','epsapp.views.reportdetail',name='reportdetail'), 
    url(r'^appeps/gerente/rutas$','epsapp.views.routes',name='routes'),                                                     #Rutas
    url(r'^appeps/gerente/eventos$','epsapp.views.logs',name='logs'),                                                       #Registro de eventos
    url(r'^appeps/gerente/eventos/filtrar$','epsapp.views.filterlog',name='filterlog'),                                     #Filtrar entradas del log
    url(r'^appeps/gerente/eventos/borrar/(?P<logentryid>\d+)$','epsapp.views.deletelogentry',name='deletelogentry'),        #Eliminar un entrada del log

    ###------------------------------------------------------Empleados--------------------------------------###
    
    url(r'^appeps/despachador$','epsapp.views.dispatcher',name='dispatcher'),                                               #Principal despachador

    url(r'^appeps/despachador/solicitudes$','epsapp.views.alldelrequest_disp',name='alldelrequest_disp'),                   #Todas las solicitudes
    url(r'^appeps/despachador/solicitudes/(?P<requestid>\d+)$','epsapp.views.requestdetail_disp',name='requestdetail_disp'),#Una solicitud
    url(r'^appeps/despachador/solicitudes/borrar/(?P<requestid>\d+)$','epsapp.views.deletereq',name='deletereq'),           #Eliminar solicitud
    url(r'^appeps/despachador/solicitudes/actualizar/(?P<requestid>\d+)$','epsapp.views.updatereq_disp',name='updatereq_disp'), #Actualizar solicitud
    url(r'^appeps/despachador/buscar$','epsapp.views.searchreq',name='searchreq'),                                          #Buscar solicitud
    
    ###------------------------------------------------------Otros--------------------------------------###

    url(r'^appeps/error$','epsapp.views.exception',name='exception'),                                                       #Excepcion o error
    

    ###---Servicios Web:---###

    url(r'^wseps/solicitud$','epsapp.views.wsnewrequest',name='wsnewrequest'),                                             #Crear solicitud
    url(r'^wseps/solicitud/(?P<requestid>VE\d+)$','epsapp.views.wsdetailrequest',name='wsdetailrequest'),                     #Una solicitud
    url(r'^wseps/factura/(?P<billid>\d+)$','epsapp.views.wsdetailbill',name='wsdetailbill'),                     #Una factura

    ###---Administracion:---###
    url(r'^admin/', include(admin.site.urls)),
)

epsapp/models.py
from django.db import models
from datetime import timedelta, date, datetime
from django.utils.timezone import *
from django.contrib.auth.models import User

# Create your models here.

#Modelo Distribuidor para almacenar informacion
class Distributor(models.Model):
	"""docstring for Distributor"""
	
	rif = models.CharField(unique=True,max_length=50,verbose_name=u'RIF')
	dist_name = models.CharField(max_length=100,verbose_name=u'Distribuidor')

	class Meta:
		verbose_name = 'Distributor'
		verbose_name_plural = 'Distributors'

	def __unicode__(self):
		return u'%s - RIF: %s' % (
			self.dist_name,
			self.rif)
		
#Modelo Comercio
class Associated(models.Model): 
	"""docstring for Associated"""

	added = models.DateTimeField(verbose_name=u'Asociado en')
	rif = models.CharField(unique=True,max_length=50,verbose_name=u'RIF')
	assoc_name = models.CharField(max_length=100,verbose_name=u'Comercio')
	bill_webservice = models.URLField(verbose_name=u'URL del webservice')

	class Meta:
		verbose_name = 'Associated'
		verbose_name_plural = 'Associated'

	def __unicode__(self):
		return u'%s - Anadido: %s - RIF: %s' % (
			self.assoc_name,
			self.added,
			self.rif)

	def natural_key(self):
		return (self.added,self.rif,self.assoc_name)

#Modelo Ubicacion
class Location(models.Model):
	"""docstring for Location"""

	city = models.CharField(max_length=100,verbose_name=u'Ciudad')
	state = models.CharField(max_length=100,verbose_name=u'Estado')
	country = models.CharField(max_length=100,verbose_name=u'Pais')
	zip_code = models.CharField(unique=True,max_length=50,verbose_name=u'ZIP')

	class Meta:
		verbose_name = 'Location'
		verbose_name_plural = 'Locations'

	def __unicode__(self):
		return u'Ciudad: %s Estado: %s - ZIP: %s - Pais: %s' % (
			self.city,
			self.state,
			self.zip_code,
			self.country)
	
#Modelo Ruta
class Route(models.Model):
	"""docstring for Route"""
	
	destination = models.ForeignKey(Location,verbose_name=u'Destino')
	charge_x_km = models.FloatField(verbose_name=u'Costo por KM')

	class Meta:
		verbose_name = 'Route'
		verbose_name_plural = 'Routes'

	def __unicode__(self):
		return u'Ruta a %s con costo por KM de %s' % (
			self.destination,
			self.charge_x_km)

#Modelo Solicitud de envio
class DeliveryRequest(models.Model):
	"""docstring for DeliveryRequest"""
	
	request_date = models.DateTimeField(auto_now_add=True,verbose_name=u'Fecha de solicitud')
	tracking_number = models.CharField(unique=True,max_length=100,verbose_name=u'Numero de rastreo')
	delivery_date = models.DateTimeField(verbose_name=u'Fecha de entrega')
	address = models.TextField(verbose_name=u'Direccion')
	additional_info = models.TextField(blank=True,verbose_name=u'Informacion adicional')
	route = models.ForeignKey(Route,verbose_name=u'Ruta')
	associated_comm = models.ForeignKey(Associated,verbose_name=u'Comercio')

	class Meta:
		verbose_name = 'DeliveryRequest'
		verbose_name_plural = 'DeliveryRequests'

	def __unicode__(self):
		return u'%s Solicitada: %s - Tracking: %s - A: %s %s' % (
			self.id,
			self.request_date,
			self.tracking_number,
			self.route.destination,
			self.address)

#Modelo Estado
class Status(models.Model):
	"""docstring for Status"""
	DELIVERYREQUEST_STATUS = (
		('00','Recibida'),
		('01','Por despachar'),
		('02','Despachada'),
		('03','Entregada'))
	status = models.CharField(choices=DELIVERYREQUEST_STATUS,max_length=50,default='00',verbose_name=u'Estado')
	status_date = models.DateTimeField(auto_now=True,verbose_name=u'Fecha estado')
	location = models.ForeignKey(Location,verbose_name=u'Ubicacion')
	delrequest = models.ForeignKey(DeliveryRequest,verbose_name=u'Solicitud')

	class Meta:
		verbose_name = 'Status'
		verbose_name_plural = 'Status'
		ordering = ['status_date']

	def __unicode__(self):
		return u'%s %s %s' % (
			self.status,
			self.status_date,
			self.location)

#Modelo Paquete
class Package(models.Model):
	"""docstring for Package"""

	added_date = models.DateTimeField(auto_now_add=True,verbose_name=u'Agregado')
	amount = models.IntegerField(verbose_name=u'Cantidad')
	weigth = models.FloatField(verbose_name=u'Peso')
	length = models.FloatField(verbose_name=u'Largo')
	width = models.FloatField(verbose_name=u'Ancho')
	height = models.FloatField(verbose_name=u'Alto')
	description = models.TextField(blank=True,verbose_name=u'Descripcion')
	delivery_req = models.ForeignKey(DeliveryRequest,verbose_name=u'Solicitud')
	price = models.FloatField(verbose_name=u'Precio')

	class Meta:
		verbose_name = 'Package'
		verbose_name_plural = 'Packages'

	def __unicode__(self):
		return u'Cant %s - Agregado: %s - Peso: %s - Largo: %s - Ancho: %s - Alto: %s - Solicitud: %s' % (
			self.amount,
			self.added_date,
			self.weigth,
			self.length,
			self.width,
			self.height,
			self.delivery_req)

#Modelo Factura
class Bill(models.Model):
	"""docstring for Bill"""

	issuance_date = models.DateTimeField(auto_now_add=True,verbose_name=u'Generada')
	dist_rif = models.CharField(max_length=50,default='123456789',editable=False,verbose_name=u'RIF')
	dist_name = models.CharField(max_length=100,default='EPS Express',editable=False,verbose_name=u'Nombre distribuidor')
	account_number = models.CharField(max_length=100,default='0000000000000',editable=False,verbose_name=u'Numero de cuenta')
	sub_total = models.FloatField(default=0.0,editable=False,verbose_name=u'Sub-total')
	taxes = models.FloatField(default=0.0,editable=False,verbose_name=u'Impuestos')
	total = models.FloatField(default=0.0,editable=False,verbose_name=u'Total a pagar')
	expiration_date = models.DateTimeField(editable=False,verbose_name=u'Fecha de vencimiento')
	payment_date = models.DateTimeField(null=True,blank=True,verbose_name=u'Fecha de pago')
	PAYMENT_STATUS = (
		('00','Vigente'),
		('01','Cancelada'),
		('02','Vencida'),
		('03','Cancelada despues de fecha'))
	payment_status = models.CharField(max_length=50,choices=PAYMENT_STATUS,default='00',verbose_name=u'Estado del pago')
	request = models.OneToOneField(DeliveryRequest,verbose_name=u'Solicitud')

	class Meta:
		verbose_name = 'Bill'
		verbose_name_plural = 'Bills'

	def __unicode__(self):
		return u'%s - Comercio: %s - Generada: %s - Sub-total %s + Impuestos %s = Total %s - %s - Pagada el: %s - Se vence: %s - Pagar en: %s' % (
			self.request.tracking_number,
			self.request.associated_comm,
			self.issuance_date,
			self.sub_total,
			self.taxes,self.total,
			self.payment_status,
			self.payment_date,
			self.expiration_date,
			self.account_number)

	def save(self,*args,**kwargs):
		if not self.id:
			self.expiration_date = (datetime.utcnow()+timedelta(days=30)).replace(tzinfo=utc)
		super(Bill,self).save(args,kwargs)

#Modelo Tipo de empleado
class Role(models.Model):
	"""docstring for Role"""
	
	role_name = models.CharField(max_length=50,verbose_name=u'Tipo de empleado')

	class Meta:
		verbose_name = 'Role'
		verbose_name_plural = 'Roles'

	def __unicode__(self):
		return u'Rol: %s' % (self.role_name)

#Modelo Empleado
class Employee(models.Model):
	"""docstring for Employee"""

	user = models.OneToOneField(User,verbose_name=u'Usuario')
	hire_date = models.DateField(auto_now_add=True,editable=False,verbose_name=u'Fecha contratacion')
	ci = models.CharField(unique=True,max_length=50,verbose_name=u'Cedula')
	middle_name = models.CharField(max_length=50,blank=True,verbose_name=u'Segundo Nombre')
	second_last_name = models.CharField(max_length=50,blank=True,verbose_name=u'Segundo Apellido')
	phone = models.CharField(max_length=50,verbose_name=u'Telefono')
	cellphone = models.CharField(max_length=50,verbose_name=u'Celular')
	address = models.TextField(verbose_name=u'Direccion')
	role = models.ForeignKey(Role,verbose_name=u'Tipo de empleado')

	class Meta:
		verbose_name = 'Employee'
		verbose_name_plural = 'Employees'

	def __unicode__(self):
		return u'%s %s %s %s %s %s' % (self.user,self.user.first_name,self.user.last_name,self.ci,self.phone,self.role)
				
#Modelo entrada del registro
class LogEntry(models.Model):
	"""docstring for LogEntry"""

	event_date = models.DateTimeField(auto_now_add=True,verbose_name=u'Marca de tiempo')
	LOGEVENT_TYPE = (('ERR','Error'),('REQ','Solicitud'),('EMP','Empleado'),('PAY','Pago'),('GEN','General')) 
	event_type = models.CharField(choices=LOGEVENT_TYPE,max_length=50,verbose_name=u'Tipo de evento')
	event_desc = models.TextField(verbose_name=u'Descripcion')

	class Meta:
		verbose_name = 'LogEntry'
		verbose_name_plural = 'LogEntrys'

	def __unicode__(self):
		dis_datetime = self.event_date
		return u'%s %s %s' % (
			self.event_date.astimezone(tz=get_default_timezone()), 
			self.event_type,
			self.event_desc)

#Modelo Reporte
class Report(models.Model):
	"""docstring for Report"""

	date_created = models.DateTimeField(auto_now_add=True,verbose_name=u'Fecha de creacion')
	int_init = models.DateTimeField(verbose_name=u'Inicio intervalo')
	int_end = models.DateTimeField(verbose_name=u'Fin intervalo')
	REPORT_TYPES = (
		('01','Solicitudes despachadas y tiempo de despacho'),
		('02','Solicitudes pendientes y tiempo pendiente'),
		('03','Clientes ordenados por cantidad de solicitudes'),
		('04','Destinos ordenados por cantidad de solicitudes'),
		('05','Facturas ordenadas por tiempo de cancelacion'),
		('06','Facturas vigentes por cobrar'),
		('07','Facturas vencidas por cobrar'),
		)
	type = models.CharField(max_length=50,verbose_name=u'Tipo de reporte')
	pdf_path = models.FilePathField(null=True,blank=True,path="static/pdf/reports",match=".*\.pdf",verbose_name=u'Archivo PDF')
	employee = models.ForeignKey(Employee,verbose_name=u'Empleado')

	class Meta:
		verbose_name = 'Report'
		verbose_name_plural = 'Reports'

	def __unicode__(self):
		return u'Creado por: %s en %s Intervalo: %s - %s %s' % (
			self.employee,
			self.date_created,
			self.int_init,
			self.int_end,
			self.type)

#Modelo cuenta de				
class Account(models.Model): 
	"""docstring for BankAccount"""

	bank_name = models.CharField(max_length=100,verbose_name=u'Banco')

epsapp/forms.py
# -*- coding: utf-8 -*-
from django import forms
from epsapp.models import *

class LocationChoiceField(forms.ModelChoiceField):
	def label_from_instance(self, obj):
		return '%s, %s, %s, %s' % (obj.country,obj.state,obj.city,obj.zip_code)

class UpdateStatusForm(forms.Form):
	
	DELIVERYREQUEST_STATUS = (
	('00','Recibida'),
	('01','Por despachar'),
	('02','Despachada'),
	('03','Entregada'))

	status = forms.ChoiceField(choices=DELIVERYREQUEST_STATUS,label='Estado',required=True)
	location = LocationChoiceField(queryset=Location.objects.all(),empty_label=None,label='Locación',required=True)


class CreateReportForm(forms.Form):
	int_init = forms.DateTimeField(label='Inicio de intervalo')
	int_end = forms.DateTimeField(label='Fin de intervalo')
	REPORT_TYPES = (
		('01','Solicitudes despachadas y tiempo de despacho'),
		('02','Solicitudes pendientes y tiempo pendiente'),
		('03','Clientes ordenados por cantidad de solicitudes'),
		('04','Destinos ordenados por cantidad de solicitudes'),
		('05','Facturas ordenadas por tiempo de cancelacion'),
		('06','Facturas vigentes por cobrar'),
		('07','Facturas vencidas por cobrar'),
		)
	type = forms.ChoiceField(choices=REPORT_TYPES,label='Tipo de reporte',required=True)

epsapp/templates/deliveryrequest-detail-disp.html
{% extends "emptemplate.html" %}
{% load staticfiles %}


{% block title %}Sistema EPS: Gestión de solicitudes{% endblock title %}

{% block role %}
Despachador:
{% endblock role %}

{% block othercss %}
	<link rel="stylesheet" type="text/css" media="screen" href="{% static 'assets/css/empcss.css' %}"/>
{% endblock othercss %}

{% block navbarcontent %}
	<li><a href="/appeps/despachador">Inicio</a></li>
	<li class="active"><a href="/appeps/despachador/solicitudes">Gestión de Solicitudes</a></li>
	<li><a data-toggle="modal" data-target="#exitmodal">Cerrar sesión</a></li>
{% endblock navbarcontent %}

{% block modal1 %}
	<div class="modal fade" id="deletemodal">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	        <h4 class="modal-title">Eliminar solicitud</h4>
	      </div>
	      <div class="modal-body">
	        <p>¿Está seguro que desea eliminar la solicitud?</p>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
	        <a class="btn btn-primary" href="/appeps/despachador/solicitudes/borrar/{{deliveryreq.id}}">Eliminar</a>
	      </div>
	    </div><!-- /.modal-content -->
	  </div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
{% endblock modal1 %}

{% block rowscontent %}
	<div class="row">
		<div class="col-md-12">
			{% if deliveryreq %}
			<div class="bs-callout-small bs-callout-blue">
			<a class="btn btn-primary" href="/appeps/despachador/solicitudes/actualizar/{{deliveryreq.id}}" role="button">
				Actualizar estado 
				<span class="glyphicon glyphicon-map-marker">
			</a>
			<a class="btn btn-primary" href="/appeps/despachador/solicitudes/editar/{{deliveryreq.id}}" role="button">
				Editar 
				<span class="glyphicon glyphicon-pencil">
			</a>
			<a class="btn btn-primary" data-toggle="modal" data-target="#deletemodal" role="button">
				Eliminar 
				<span class="glyphicon glyphicon-trash">
			</a>
			</div>
			{% endif %}
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
		{% if deliveryreq %}
			<div class="panel panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">Solicitud: {{deliveryreq.tracking_number}} - Entrega estimada: {{deliveryreq.delivery_date}}</h3>
				</div>
				<div class="panel-body">
			    	<ul class="list-group">
			    		<li class="list-group-item">
							<h4><span class="label label-primary">Estado:</span>
							{% if deliveryreq.status_set.last.status == '00' %}
								<span class="label label-default">Recibida</span>
							{% elif deliveryreq.status_set.last.status == '01' %}
								<span class="label label-info">Por despachar</span>
							{% elif deliveryreq.status_set.last.status == '02' %}
								<span class="label label-primary">Despachada</span>
							{% elif deliveryreq.status_set.last.status == '03' %}
								<span class="label label-success">Entregada</span>
							{% endif %}	
							</h4>
						</li>
						<li class="list-group-item">
							<h4><span class="label label-primary">Datos de destino:</span></h4>
							<h5><strong>Dirección:</strong> {{deliveryreq.address}}</h5>
							<h5><strong>Ciudad:</strong> {{deliveryreq.route.destination.city}}</h5>
							<h5><strong>Código Postal:</strong> {{deliveryreq.route.destination.zip_code}}</h5>
							<h5><strong>Estado: </strong>{{deliveryreq.route.destination.state}}</h5>
							<h5><strong>País:</strong> {{deliveryreq.route.destination.country}}</h5>
						</li>
						<li class="list-group-item">
							<h4><span class="label label-primary">Paquetes:</span></h4>
							<table class="table">
								<tr>
									<th>Paquete</th>
									<th>Peso</th>
									<th>Ancho</th>
									<th>Alto</th>
									<th>Largo</th>
									<th>Descripción</th>
								</tr>
								{% for pack in deliveryreq.package_set.all  %}
								<tr>
									<td>{{ forloop.counter }}</td>
									<td>{{ pack.weigth }} Kg.</td>
									<td>{{ pack.width }} Cm. </td>
									<td>{{ pack.height }} Cm.</td>
									<td>{{ pack.length }} Cm.</td>
									<td>{{ pack.description }}</td>
								</tr>
								{% endfor %}
							</table>
						</li>
						<li class="list-group-item">
							<h4><span class="label label-primary">Historial:</span></h4>
							<table class="table">
								<tr>
									<th>Fecha</th>
									<th>Estado</th>
									<th>Ciudad</th>
									<th>Provincia</th>
									<th>País</th>
								</tr>
								{% for dr in deliveryreq.status_set.all  %}
								<tr>
									<td>{{dr.status_date}}</td>
									{% if dr.status == '00' %}
										<td><span class="label label-default">Recibida</span></td>
									{% elif dr.status == '01' %}
										<td><span class="label label-info">Por despachar</span></td>
									{% elif dr.status == '02' %}
										<td><span class="label label-primary">Despachada</span></td>
									{% elif dr.status == '03' %}
										<td><span class="label label-success">Entregada</span></td>
									{% endif %}	
									<td>{{dr.location.city}}</td>
									<td>{{dr.location.state}}</td>
									<td>{{dr.location.country}}</td>
								</tr>
								{% endfor %}
							</table>
						</li>
						<li class="list-group-item">
							<h4><span class="label label-primary">Información adicional:</span></h4>
							<p>{{deliveryreq.additional_info}}</p>
						</li>
					</ul>
				</div>
			</div>
			{% endif %}
		</div>
	</div>
{% endblock rowscontent %}

epsapp/templates/reports-man.html
{% extends "emptemplate.html" %}
{% load staticfiles %}


{% block title %}Sistema EPS: Reportes{% endblock title %}

{% block role %}
	Gerente:
{% endblock role %}

{% block othercss %}
	<link rel="stylesheet" type="text/css" media="screen" href="{% static 'assets/css/empcss.css' %}"/>
	<link rel="stylesheet" type="text/css" media="screen" href="{% static 'assets/jquery-ui-1.10.4/themes/base/jquery-ui.css' %}"/>
	<link rel="stylesheet" type="text/css" media="screen" href="{% static 'assets/css/jquery-ui-timepicker-addon.css' %}"/>
{% endblock othercss %}


{% block headscripts %}

	<script src="{% static 'assets/jquery-ui-1.10.4/ui/jquery-ui.js' %}"></script>
	<script src="{% static 'assets/js/jquery-ui-timepicker-addon.js' %}"></script>
	<script src="{% static 'assets/jquery-ui-1.10.4/ui/i18n/jquery.ui.datepicker-es.js' %}"></script>
	<script>
	$( document ).ready(function() {
	  //$( "#id_int_init" ).attr("required","true");
	  //$( "#id_int_end" ).attr("required","true");
	  $(function() {
	    $( "#id_int_init" ).datetimepicker({
	      timeFormat: 'HH:mm:ss',
	      changeMonth: true,
	      changeYear: true,
	      controlType: 'select',
	      timeText: 'Horario',
	      hourText: 'Hora',
	      minuteText: 'Minutos',
	      secondText: 'Segundos',
	      currentText: 'Ahora',
	      closeText: 'Cerrar'
	    });
	    $( "#id_int_end" ).datetimepicker({
	      timeFormat: 'HH:mm:ss',
	      changeMonth: true,
	      changeYear: true,
	      controlType: 'select',
	      timeText: 'Horario',
	      hourText: 'Hora',
	      minuteText: 'Minutos',
	      secondText: 'Segundos',
	      currentText: 'Ahora',
	      closeText: 'Cerrar'
	    });
	  });
	});
		
  	</script>
{% endblock headscripts %}

{% block navbarcontent %}
	<li><a href="/appeps/gerente">Inicio</a></li>
	<li><a href="/appeps/gerente/solicitudes">Gestión de Solicitudes</a></li>
	<li><a href="/appeps/gerente/facturas">Facturas</a></li>
	<li class="active"><a href="#">Reportes</a></li>
	<!--<li><a href="/appeps/gerente/rutas">Rutas</a></li>-->
	<li><a href="/appeps/gerente/eventos">Registro de eventos</a></li>
	<li><a data-toggle="modal" data-target="#exitmodal">Cerrar sesión</a></li>
{% endblock navbarcontent %}

{% block modal1 %}
	<div class="modal fade" id="createreport">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	        <h4 class="modal-title">Crear nuevo reporte</h4>
	      </div>
	      <div class="modal-body">
	        <form action="/appeps/gerente/reportes/crear" method="post" id="newrepform">{% csrf_token %}
	        	{{ form.as_p }}
	        </form>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
	        <button class="btn btn-primary" type="submit" form="newrepform">Crear</button>
	      </div>
	    </div><!-- /.modal-content -->
	  </div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
{% endblock modal1 %}

{% block rowscontent %}
	<div class="row">
		<div class="col-md-12">
			<div class="bs-callout-small bs-callout-blue">
				<a class="btn btn-primary" data-toggle="modal" data-target="#createreport" role="button">
				Nuevo Reporte 
				<span class="glyphicon glyphicon-plus">
			</a>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<ul>
			{% if reports %}
			{% for report in reports %}
			<li><a href="/appeps/gerente/reportes/{{report.id}}">{{ report }}</a></li>
			{% endfor %}
			{% endif %}</ul>
		</div>
	</div>
{% endblock rowscontent %}